### PR TITLE
Explicitly add gateway config url to our JMX configs

### PR DESCRIPTION
**Pull request by tschieggm**
- break apart AWS Prod configs (/Stackdriver) from gprod configs(/google-cloud-monitoring)
- add explicit url setting for pointing to the correct gateway

@ekilby @katzj 

Question: Are there any docs I will need to update links to / should I update the README?

### CODE REVIEW

**Comment by ekilby** [comment]
I'd set the detectInstance to GCE for the Cloud Monitoring detect files.

**Comment by tschieggm** [comment]
Yeah, you mentioned that in person, apologizes for forgetting. Updating PR now.

**Comment by ekilby** [comment]
LGTM codewise

My only comment would be to coordinate merging this with updating any docs that point to the existing folders.  May be worth talking to Amanda first.

**Comment by tschieggm** [comment]
@ekilby - Definitely, to quote [b/19000382](https://b.corp.google.com/u/0/issues/19000382)

> I'll update this ticket when its merged to master and get in touch with @amandalewis in person regarding changes to docs and support for GCM -> Stackdriver custom metrics.

**Comment by katzj** [comment]
You, sir, are a gentleman and a scholar.

LGTM

**Pull request merged**
