### PR TITLE
Add the protocol to the URLs in Google jmxtrans JSON configs.

### PR DESCRIPTION
**Pull request by igorpeshansky**

### CODE REVIEW

**Comment by tschieggm** [comment]
This LGTM from the `google-cloud-monitoring` side. However, the configs on the `stackdriver` side should also be updated to include this fix.

**Comment by igorpeshansky** [comment]
Done. Will squash into one commit before the merge. PTAL.

**Comment by tschieggm** [comment]
LGTM, thanks for the patch.

**Comment by igorpeshansky** [comment]
Squashed, ready to merge.

**Pull request merged**
